from fpdf import FPDF
from pathlib import Path
from datetime import datetime
import textwrap
from core.schemas import SessionAnalysis, SessionData
from reasoning.analyzer import InterviewAnalyzer
import logging

logger = logging.getLogger(__name__)

class PDFReportGenerator(FPDF):
    def __init__(self, session_data: SessionData, analysis: SessionAnalysis):
        super().__init__()
        self.session_data = session_data
        self.analysis = analysis
        self.set_auto_page_break(auto=True, margin=15)
        # Using standard fonts to avoid path issues
        
        # Colors
        self.primary_color = (0, 51, 102) # Dark Blue
        self.secondary_color = (100, 100, 100) # Grey
        self.accent_color = (0, 153, 76) # Green for good scores

    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(*self.primary_color)
        self.cell(0, 10, 'Interview Intelligence Report', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        self.cell(0, 10, 'Generated by Dextora AI', 0, 0, 'R')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(0, 0, 0)
        self.set_fill_color(240, 248, 255) # Alice Blue
        self.cell(0, 8, f'  {title}', 0, 1, 'L', True)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 5, text)
        self.ln()
        
    def add_score_bar(self, label, score):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        self.cell(60, 6, label, 0, 0)
        
        # Draw bar
        bar_x = self.get_x()
        bar_y = self.get_y()
        bar_width = 80
        bar_height = 5
        
        # Background
        self.set_fill_color(230, 230, 230)
        self.rect(bar_x, bar_y + 1, bar_width, bar_height, 'F')
        
        # Overlay
        if score is None: score = 0
        filled_width = (score / 100) * bar_width
        
        if score >= 75:
            self.set_fill_color(0, 153, 76) # Green
        elif score >= 50:
            self.set_fill_color(255, 165, 0) # Orange
        else:
            self.set_fill_color(204, 0, 0) # Red
            
        self.rect(bar_x, bar_y + 1, filled_width, bar_height, 'F')
        
        # Score Label
        self.set_x(bar_x + bar_width + 5)
        self.cell(20, 6, f"{score}/100", 0, 1)

    def generate_soft_skills_analysis(self):
        """
        Uses LLM to generate specific analysis for Attitude, Kindness, Leadership, etc.
        """
        analyzer = InterviewAnalyzer()
        
        # Gather text content for context (Last 10 Q&A pairs for brevity/relevance)
        full_transcript = ""
        if self.session_data.question_answer_pairs:
             recent_pairs = self.session_data.question_answer_pairs[-10:]
             for qa in recent_pairs:
                 full_transcript += f"Q: {qa.question_text}\nA: {qa.response_text}\n\n"
        
        prompt = f"""
        Analyze the following interview conversation snippets and provide a specific assessment of the candidate's soft skills.
        
        TRANSCRIPT SNIPPET:
        {full_transcript[:10000]} 
        
        INSTRUCTIONS:
        Provide a concise paragraph (3-4 sentences) for each of the following traits. 
        Focus on observable behaviors.
        
        1. Attitude (Positivity, resilience)
        2. Kindness & Empathy (Interpersonal warmth)
        3. Leadership Potential (Initiative, influence)
        
        Output format:
        **Attitude**: [Text]
        **Kindness**: [Text]
        **Leadership**: [Text]
        """
        
        # Check LLM connection first
        try:
            response = analyzer._call_llm(prompt)
            # Remove asterisks for cleaner PDF
            response = response.replace("**", "")
            return response
        except Exception as e:
            logger.error(f"LLM Generation failed: {e}")
            return "Analysis pending."

    def create_report(self):
        self.add_page()
        
        # Metadata
        self.set_font('Helvetica', '', 11)
        name = self.session_data.metadata.interviewee_name or 'Unknown'
        date_str = self.session_data.metadata.created_at.strftime('%Y-%m-%d %H:%M')
        self.cell(0, 6, f"Candidate: {name}", ln=True)
        self.cell(0, 6, f"Date: {date_str}", ln=True)
        self.ln(10)
        
        # 1. Executive Summary
        self.chapter_title("Executive Summary")
        if self.analysis.executive_summary:
            # Clean summary text
            summary_text = self.analysis.executive_summary.encode('latin-1', 'replace').decode('latin-1')
            self.chapter_body(summary_text)
        else:
            self.chapter_body("No executive summary available.")
            
        # 2. Behavioral Scores
        self.chapter_title("Key Behavioral Metrics")
        self.ln(2)
        
        scores = [
            ("Integrity", self.analysis.integrity_score),
            ("Confidence", self.analysis.confidence_score),
            ("Mental Alertness", getattr(self.analysis, 'mental_alertness_score', 0)),
            ("Critical Assimilation", getattr(self.analysis, 'critical_assimilation_score', 0)),
            ("Clear Exposition", getattr(self.analysis, 'clear_exposition_score', 0)),
            ("Balance of Judgment", getattr(self.analysis, 'balance_judgment_score', 0)),
            ("Social Cohesion", getattr(self.analysis, 'social_cohesion_score', 0)),
            ("Leadership Potential", getattr(self.analysis, 'leadership_score', 0) if hasattr(self.analysis, 'leadership_score') else 0.0), # Removed fallback
        ]
        
        for label, score in scores:
            self.add_score_bar(label, score)
        self.ln(5)
        
        # 3. Soft Skills Analysis (LLM Generated)
        self.chapter_title("Deep Soft Skills Analysis")
        # Generate text
        soft_skills_text = self.generate_soft_skills_analysis()
        
        # Handle Latin-1 encoding issues common in FPDF
        soft_skills_text = soft_skills_text.encode('latin-1', 'replace').decode('latin-1')
        
        self.chapter_body(soft_skills_text)
        
        # 4. Conclusion
        self.ln(5)
        self.set_font('Helvetica', 'I', 10)
        self.multi_cell(0, 5, "This report was generated automatically by Dextora AI based on behavioral and verbal analysis.")
         
    def save(self, path):
        self.output(str(path))
